name: BOM Tracker

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'requirements.txt'
      - 'Pipfile'
      - 'go.mod'
      - 'go.sum'
      - 'Cargo.toml'
      - 'Cargo.lock'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sbom-audit:
    name: SBOM - Software Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run SBOM audit
        id: sbom
        run: |
          # Install query runner dependencies
          cd $GITHUB_WORKSPACE/../meta-templates
          npm install --no-save

          # Run SBOM audit
          node query-runner.js sbom_audit \
            --repo ${{ github.repository }} \
            --format json > $GITHUB_WORKSPACE/sbom-report.json

          # Check for vulnerabilities
          CRITICAL=$(jq '[.data.dependencies[]? | select(.vulnerabilities[]?.severity == "CRITICAL")] | length' $GITHUB_WORKSPACE/sbom-report.json)
          HIGH=$(jq '[.data.dependencies[]? | select(.vulnerabilities[]?.severity == "HIGH")] | length' $GITHUB_WORKSPACE/sbom-report.json)

          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
          echo "high=$HIGH" >> $GITHUB_OUTPUT

          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            echo "status=failed" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "status=passed" >> $GITHUB_OUTPUT
          fi

      - name: Upload SBOM report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom-report.json
          retention-days: 90

      - name: Create security issue
        if: steps.sbom.outputs.status == 'failed'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('sbom-report.json', 'utf8'));

            const vulns = report.data.dependencies
              .filter(d => d.vulnerabilities && d.vulnerabilities.length > 0)
              .map(d => ({
                name: d.name,
                version: d.version,
                vulns: d.vulnerabilities
              }));

            const body = `# ðŸ”’ Security Vulnerabilities Found

            **Critical:** ${{ steps.sbom.outputs.critical }}
            **High:** ${{ steps.sbom.outputs.high }}

            ## Affected Dependencies

            ${vulns.map(v => `
            ### ${v.name}@${v.version}
            ${v.vulns.map(vuln => `
            - **${vuln.cve_id}** (${vuln.severity})
              - ${vuln.advisory?.summary || 'No summary'}
              - Fixed in: ${vuln.fixed_version || 'Unknown'}
            `).join('\n')}
            `).join('\n')}

            ## Next Steps

            1. Review vulnerabilities above
            2. Update affected dependencies
            3. Re-run \`npm audit fix\` or equivalent
            4. Verify fixes with \`npm test\`

            ---
            *Auto-generated by BOM Tracker - ${new Date().toISOString()}*
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'ðŸ”’ Security: Critical/High CVEs in dependencies',
              body: body,
              labels: ['security', 'sbom', 'urgent']
            });

  cbom-compliance:
    name: CBOM - Compliance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check UAE PDPL compliance
        run: |
          cd $GITHUB_WORKSPACE/../meta-templates
          npm install --no-save

          node query-runner.js cbom_compliance \
            --jurisdiction UAE \
            --product ${{ github.repository }} \
            --format json > $GITHUB_WORKSPACE/cbom-uae-report.json

          SCORE=$(jq -r '.privacy_score' $GITHUB_WORKSPACE/cbom-uae-report.json)
          echo "UAE PDPL Privacy Score: $SCORE"

          if [ $(echo "$SCORE < 85" | bc) -eq 1 ]; then
            echo "âš ï¸  Privacy score below threshold (85)"
            exit 1
          fi

      - name: Check GDPR compliance
        run: |
          cd $GITHUB_WORKSPACE/../meta-templates

          node query-runner.js cbom_compliance \
            --jurisdiction EU \
            --product ${{ github.repository }} \
            --format json > $GITHUB_WORKSPACE/cbom-eu-report.json

      - name: Upload compliance reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cbom-reports
          path: |
            cbom-uae-report.json
            cbom-eu-report.json
          retention-days: 365

      - name: Create compliance issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const uaeReport = JSON.parse(fs.readFileSync('cbom-uae-report.json', 'utf8'));

            const body = `# âš–ï¸  Compliance Issues Found

            **Jurisdiction:** UAE PDPL
            **Privacy Score:** ${uaeReport.privacy_score}/100 (threshold: 85)
            **Status:** ${uaeReport.compliance_status}

            ## Requirements

            ${uaeReport.requirements.map(r => `
            - **${r.article}:** ${r.status}
              - Evidence: ${r.evidence || 'None'}
            `).join('\n')}

            ${uaeReport.violations.length > 0 ? `
            ## Violations

            ${uaeReport.violations.map(v => `
            - **${v.description}** (Severity: ${v.severity})
              - Remediation: ${v.remediation}
            `).join('\n')}
            ` : ''}

            ## Next Steps

            1. Review violations above
            2. Implement remediation steps
            3. Update compliance documentation
            4. Re-run compliance check

            ---
            *Auto-generated by BOM Tracker*
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'âš–ï¸ Compliance: UAE PDPL issues found',
              body: body,
              labels: ['compliance', 'cbom', 'pdpl']
            });

  obom-metrics:
    name: OBOM - Performance Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Collect metrics
        run: |
          cd $GITHUB_WORKSPACE/../meta-templates
          npm install --no-save

          node query-runner.js obom_metrics \
            --service ${{ github.repository }} \
            --days 7 \
            --format json > $GITHUB_WORKSPACE/obom-report.json

          # Extract key metrics
          COST=$(jq -r '.total_cost_7d // "0"' $GITHUB_WORKSPACE/obom-report.json)
          echo "Weekly cost: \$$COST"

      - name: Upload metrics
        uses: actions/upload-artifact@v4
        with:
          name: obom-metrics
          path: obom-report.json
          retention-days: 90

      - name: Alert on cost anomaly
        run: |
          COST=$(jq -r '.total_cost_7d // "0"' obom-report.json)
          THRESHOLD=1000  # $1000 weekly threshold

          if [ $(echo "$COST > $THRESHOLD" | bc) -eq 1 ]; then
            echo "âš ï¸  Cost exceeds threshold: \$$COST > \$$THRESHOLD"
            gh issue create \
              --title "ðŸ’° Cost Alert: Weekly spend at \$$COST" \
              --body "Observability metrics show weekly cost of \$$COST, exceeding threshold of \$$THRESHOLD. Review usage patterns." \
              --label "obom,cost,alert"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  wbom-pipelines:
    name: WBOM - Workflow Health
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check workflow health
        run: |
          cd $GITHUB_WORKSPACE/../meta-templates
          npm install --no-save

          node query-runner.js wbom_pipelines \
            --workflows ${{ github.repository }} \
            --format json > $GITHUB_WORKSPACE/wbom-report.json

          # Check success rate
          SUCCESS_RATE=$(jq -r '.workflows[0].success_rate // "1"' $GITHUB_WORKSPACE/wbom-report.json)
          echo "Workflow success rate: $SUCCESS_RATE"

          if [ $(echo "$SUCCESS_RATE < 0.95" | bc) -eq 1 ]; then
            echo "âš ï¸  Success rate below 95%"
            exit 1
          fi

      - name: Upload workflow health
        uses: actions/upload-artifact@v4
        with:
          name: wbom-health
          path: wbom-report.json
          retention-days: 90

  telemetry-push:
    name: Push Telemetry
    runs-on: ubuntu-latest
    needs: [sbom-audit, cbom-compliance, obom-metrics, wbom-pipelines]
    if: always()
    steps:
      - name: Download all reports
        uses: actions/download-artifact@v4

      - name: Combine reports
        run: |
          jq -s '
            {
              timestamp: now | todate,
              repository: "${{ github.repository }}",
              workflow_run_id: "${{ github.run_id }}",
              sbom: .[0],
              cbom: .[1],
              obom: .[2],
              wbom: .[3]
            }
          ' sbom-report/sbom-report.json \
            cbom-reports/cbom-uae-report.json \
            obom-metrics/obom-report.json \
            wbom-health/wbom-report.json \
            > combined-bom-report.json

      - name: Push to telemetry endpoint
        run: |
          curl -X POST https://telemetry.maestro.ae/api/v1/ingest \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.TELEMETRY_TOKEN }}" \
            -d @combined-bom-report.json || echo "Telemetry push failed (non-blocking)"

      - name: Notify Slack
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "ðŸš¨ BOM Tracker failed for ${{ github.repository }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*BOM Tracker Alert*\n\nRepository: `${{ github.repository }}`\nWorkflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                  }
                }
              ]
            }
